name: Build and Run Dockerfile on Self-Hosted Runner

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  build-and-run:
    name: Build and Run Dockerfile
    runs-on: [self-hosted, linux, contabo]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t portfolio-app-image .

      - name: Run Docker container
        run: |
          docker rm -f portfolio-server 2>/dev/null || true
          docker run -d --restart unless-stopped -p 3000:3000 --name portfolio-server portfolio-app-image
